# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets,QtSvg
from PyQt5.QtCore import QEventLoop,QTimer
from PyQt5.QtCore import Qt,QPoint
from PyQt5.QtWidgets  import QDesktopWidget
import os 
import sys
from progressdialog import Ui_SplashWindow


cd = os.path.dirname(os.path.abspath(sys.argv[0]))


class Ui_MiniWindow(object):
    def setupUi(self, MiniWindow,MainWindow):
        MiniWindow.setObjectName("MiniWindow")
        MiniWindow.resize(400, 70)
        MiniWindow.setWindowFlag(Qt.FramelessWindowHint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MiniWindow.sizePolicy().hasHeightForWidth())
        MiniWindow.setSizePolicy(sizePolicy)
        MiniWindow.setMaximumSize(QtCore.QSize(400, 70))
        MiniWindow.setMinimumSize(QtCore.QSize(400,70))
        MiniWindow.setStyleSheet(
                # "*{\n"
                #     "border-radius:10px;\n"
                # "}\n"
                "#centralwidget{\n"
                    "background:#414141;\n"
                    "border:2px solid #FFD369;\n"
                    "border-radius:3px;\n"
                "}"
                "#frame{\n"
                    "background:#2e2e2e;\n"
                    "border:2px solid #FFD369;\n"
                    "border-radius:10px;\n"
                "}\n"
                "#frame_2{\n"
                    "background:#414141;\n"
                "}"
                "#pushButton{\n"
                    "background:#2e2e2e;\n"
                "}\n"
                "#searchButton{\n"
                    "background:#2e2e2e;\n"
                    "border:2px solid #2e2e2e;\n"
                "}\n"
                "#exitButton{\n"
                    "background:#2e2e2e;\n"
                    "border:2px solid #2e2e2e;\n"
                "}\n"
                "#extraButton{\n"
                    "background:#2e2e2e;\n"
                    "border:2px solid #FFD369;\n"
                    "border-radius:10px;\n"
                "}\n"
                "#dragLabel{\n"
                    "border:2px solid #2e2e2e;\n"
                    "border-left-color: #FFD369;\n"
                "}\n"
        )
        
        self.centralwidget = QtWidgets.QWidget(MiniWindow)
        self.centralwidget.setStyleSheet("background:#2e2e2e;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(0,0,0,0)

        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(50, 50))
        self.frame.setMaximumSize(QtCore.QSize(50, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setText("")
        self.pushButton.clicked.connect(lambda _: self.showMainWindow(MiniWindow,MainWindow))
        icon = QtGui.QIcon(cd+"/resource/Breeze KDE-Story-Dark/actions/22/arrow-down-double.svg")
        # icon.addPixmap(QtGui.QPixmap(cd+"/resource/Breeze KDE-Story-Dark/actions/22/arrow-down-double.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setCheckable(True)
        self.pushButton.setAutoExclusive(True)
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.frame)

        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(330,60))
        self.frame_2.setMaximumSize(QtCore.QSize(330,60))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.widget = QtWidgets.QWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(40, 40))
        self.widget.setObjectName("widget")
        self.horizontalSpacer = QtWidgets.QSpacerItem(20,20,QtWidgets.QSizePolicy.Fixed,QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_3.addSpacerItem(self.horizontalSpacer)
        self.horizontalLayout_3.addWidget(self.widget)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.horizontalLayout_4.setContentsMargins(0,0,0,0)
        self.searchButton = QtWidgets.QPushButton(self.widget)
        self.searchButton.setStyleSheet('')
        self.searchButton.setText('')
        self.searchButton.setMinimumSize(QtCore.QSize(40,40))
        self.searchButton.setMaximumSize(QtCore.QSize(40,40))
        icon =  QtGui.QIcon(cd+'/resource/Breeze KDE-Story-Dark/actions/16/search.svg')
        self.searchButton.setIcon(icon)
        self.searchButton.setIconSize(1* QtCore.QSize(self.searchButton.width(),self.searchButton.height()))
        self.searchButton.setFlat(True)
        self.searchButton.setObjectName('searchButton')
        self.searchButton.setCheckable(True)
        self.searchButton.setAutoExclusive(True)
        self.horizontalLayout_4.addWidget(self.searchButton)
        # self.searchButton.clicked.connect(lambda _: self.printLineEditTextValue())

        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(40, 40))
        self.widget_2.setMaximumSize(QtCore.QSize(40,40))
        self.widget_2.setObjectName("widget_2")
        self.horizontalSpacer = QtWidgets.QSpacerItem(40,20,QtWidgets.QSizePolicy.Fixed,QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_3.addSpacerItem(self.horizontalSpacer)
        self.horizontalLayout_3.addWidget(self.widget_2)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setObjectName('horizontalLayout_5')
        self.horizontalLayout_5.setContentsMargins(0,0,0,0)
        self.extraButton = QtWidgets.QPushButton(self.widget_2)
        self.extraButton.setStyleSheet('')
        self.extraButton.setText('')
        self.extraButton.setMinimumSize(QtCore.QSize(40,40))
        self.extraButton.setMaximumSize(QtCore.QSize(40,40))
        icon =  QtGui.QIcon(cd+'/resource/Breeze KDE-Story-Dark/actions/16/search.svg')
        self.extraButton.setIcon(icon)
        self.extraButton.setIconSize(1* QtCore.QSize(self.extraButton.width(),self.extraButton.height()))
        self.extraButton.setFlat(True)
        self.extraButton.setObjectName('extraButton')
        self.extraButton.setCheckable(True)
        self.extraButton.setAutoExclusive(True)
        self.horizontalLayout_5.addWidget(self.extraButton)
        # self.extraButton.clicked.connect(lambda _: self.printLineEditTextValue())



        self.widget_3 = QtWidgets.QWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMaximumSize(QtCore.QSize(40,40))
        self.widget_3.setMinimumSize(QtCore.QSize(40, 40))
        self.widget_3.setObjectName("widget_3")
        self.horizontalSpacer = QtWidgets.QSpacerItem(40,20,QtWidgets.QSizePolicy.Fixed,QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_3.addSpacerItem(self.horizontalSpacer)
        self.horizontalLayout_3.addWidget(self.widget_3)

        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setObjectName('horizontalLayout_6')
        self.horizontalLayout_6.setContentsMargins(0,0,0,0)
        self.exitButton = QtWidgets.QPushButton(self.widget_3)
        self.exitButton.setStyleSheet('')
        self.exitButton.setText('')
        self.exitButton.setMinimumSize(QtCore.QSize(40,40))
        self.exitButton.setMaximumSize(QtCore.QSize(40,40))
        icon =  QtGui.QIcon(cd+'/resource/Breeze KDE-Story-Dark/actions/16/kontes_close.svg')
        self.exitButton.setIcon(icon)
        self.exitButton.setIconSize(1* QtCore.QSize(self.exitButton.width(),self.exitButton.height()))
        self.exitButton.setFlat(True)
        self.exitButton.setObjectName('exitButton')
        self.exitButton.setCheckable(True)
        self.exitButton.setAutoExclusive(True)
        self.horizontalLayout_6.addWidget(self.exitButton)
        self.exitButton.clicked.connect(lambda _: self.closeSplash(MiniWindow,MainWindow))

        self.dragLabel = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dragLabel.sizePolicy().hasHeightForWidth())
        self.dragLabel.setSizePolicy(sizePolicy)
        self.dragLabel.setMaximumSize(QtCore.QSize(30,60))
        self.dragLabel.setMinimumSize(QtCore.QSize(30, 60))
        self.dragLabel.setObjectName("dragLabel")
        self.dragLabel.setPixmap(QtGui.QPixmap(cd+"/resource/Breeze KDE-Story-Dark/actions/24/drag-surface.svg"))
        self.horizontalSpacer = QtWidgets.QSpacerItem(40,20,QtWidgets.QSizePolicy.Expanding,QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_3.addSpacerItem(self.horizontalSpacer)
        self.horizontalLayout_3.addWidget(self.dragLabel)
        self.horizontalLayout.addWidget(self.frame_2)
        MiniWindow.setCentralWidget(self.centralwidget)
   
        self.retranslateUi(MiniWindow)
        QtCore.QMetaObject.connectSlotsByName(MiniWindow)


    def generateSplash(self,text):
        self.splashwindow = QtWidgets.QMainWindow()
        self.splash = Ui_SplashWindow()
        self.splash.setupUi(self.splashwindow)
        self.splash.label.setStyleSheet(
            'font-family:"Courier New";\n'
            'font-size:42px;'
            )
        self.splash.label.setText(text)
        self.splashwindow.show()


    def closeSplash(self,miniWindow,MainWindow):
        self.generateSplash(text="Closing please wait a moment")
        self.splash.animation.finished.connect(lambda:self.closeWindow(miniWindow,MainWindow))

    def closeWindow(self,miniWindow,main_window):
        self.splashwindow.close()
        miniWindow.close()
        main_window.close()

    def showMainWindow(self,MiniWindow,main_window):
        MiniWindow.hide()
        main_window.show()

    def retranslateUi(self, MiniWindow):
        _translate = QtCore.QCoreApplication.translate
        MiniWindow.setWindowTitle(_translate("MiniWindow", "MainWindow"))
    
    def center(self):
        qr = self.frameGeometry()
        cp = QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        self.move(qr.topLeft())
    def mousePressEvent(self,event):
        self.oldPos = event.globalPos()
    def mouseMoveEvent(self, event):
        delta = QPoint (event.globalPos() - self.oldPos)
        self.move(self.x() + delta.x(), self.y() + delta.y())
        self.oldPos = event.globalPos()


    # def printLineEditTextValue(self):

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)

    MiniWindow = QtWidgets.QMainWindow()
    ui = Ui_MiniWindow()
    ui.setupUi(MiniWindow,None)

    MiniWindow.show()
    
    sys.exit(app.exec_())